### PR TITLE
Use global properties from android/build.gradle

### PR DESCRIPTION
**Pull request by andidev**
Use global properties from android/build.gradle if they exists

### CODE REVIEW

**Comment by skb1129** [comment]
@Kerumen This is required in a new release!

**Comment by Kerumen** [comment]
@andidev Can you use a safe accessor as [react-native-video](https://github.com/react-native-community/react-native-video/blob/master/android/build.gradle#L3-L5)? Thanks!

**Comment by Kerumen** [comment]
In order to move forward and release a new version of the library, I went ahead and did the change myself (https://github.com/Kerumen/react-native-awesome-card-io/commit/bf817aedde1ea7d8b67b627812e500ac6ed568b6).

Thanks for your contribution anyway.

**Comment by skb1129** [comment]
@Kerumen Thanks a lot!

**Pull request closed without merging**
