### PR TITLE
Fix android rn module

### PR DESCRIPTION
**Pull request by diogoguimaraes**
This pull request fixes the android react-native module.

### CODE REVIEW

**Comment by Kerumen** [comment]
This change was introduced in `v0.3.0` (https://github.com/Kerumen/react-native-awesome-card-io/commit/f54ed4b965fddd6f26c4504f3442bdaa60e10833) to support React Native 0.33.

If you use a previous version of RN, stick with a `v0.2.0` of this library.

**Comment by diogoguimaraes** [comment]
I'm using `v0.41.2`of RN and if this change was introduced in `v0.3.0`then you've got a regression issue because I can't run the android version of my app using `v0.6.1` of `react-native-awesome-card-io`. 
Can you please double check it? 

Thanks.

**Comment by Kerumen** [comment]
I've just generated a project with the latest RN and it's working fine. The `onActivityResult` has this signature:

```java
public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data)
```

Ensure you are using `compile "com.facebook.react:react-native:+"` in your `build.gradle` and run `./gradlew clean`.

**Comment by diogoguimaraes** [comment]
I've ensured all your recommendations and still have the following output when running the app:
```
RNCardIOModule.java:19: error: RNCardIOModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class RNCardIOModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOModule.java:102: error: method does not override or implement a method from a supertype
  @Override
  ^
node_modules/react-native-awesome-card-io/android/src/main/java/com/cardio/RNCardIOModule.java:124: error: method does not override or implement a method from a supertype
  @Override
  ^
3 errors
:react-native-awesome-card-io:compileReleaseJavaWithJavac FAILED
```
Do you have any other suggestions? This is weird because the signature is in fact the one you mentioned but I can't build it at all.

**Comment by Kerumen** [comment]
The error you get is about `public void onNewIntent(Intent intent)`.

As a temporary fix you can remove the `@Override` annotation to build your project.
But, once again, it's working fine on my side and if you look at the `ActivityEventListener` [source code](https://github.com/facebook/react-native/blob/24d34fe203a341b678e00ab4316e8838c50d2be9/ReactAndroid/src/main/java/com/facebook/react/bridge/ActivityEventListener.java#L22) in RN, you will see the method declared.

**Comment by diogoguimaraes** [comment]
Just a quick update, the problem had nothing to do with the code. It was not working because I have a different project structure and the maven url was wrong.
```
allprojects {
    repositories {
        jcenter()
        maven { url "$projectDir/../node_modules/react-native/android" }
    }
}
```

Anyway thank you for your time.

**Pull request closed without merging**
