### PR TITLE
Now installing CardIO with Cocoapods

### PR DESCRIPTION
**Pull request by SudoPlz**
- This is safer because everyone trusts the pod, while not many people trust a static .a file in the source
- We don't have to download a 99mb static library file

### CODE REVIEW

**Comment by jmikulka** [comment]
@Kerumen this PR is must-have. Could you please review it, and potentially merge it?

**Comment by jmikulka** [comment]
@SudoPlz Hey, we've done similar improvement to fetch the CardIO pod directly from Cocoapods. You can check it here: https://github.com/Skyscanner/react-native-awesome-card-io/commit/c87d8477c36a61e19b8814a0decb9c65130d2b95.

It works beautifully, I see that we've forgot to update the xcodeproj file though.

**Comment by SudoPlz** [comment]
oh nice, I'm happy that worked on your end @jmikulka

**Comment by jmikulka** [comment]
@SudoPlz could you please update your PR according to my commit, pls:
* we can remove changes in `README.md`
* remove `ios/CardIO` directory
* no additional changes in `ios/*.h` and `ios/*.m` files are needed
* please, update the `*.xcodeproj` files (I didn't do it in mine)
* please, update the `*.podspec` according to my commit

Many thanks, 🎉

**Comment by Kerumen** [comment]
This was done in https://github.com/Kerumen/react-native-awesome-card-io/pull/145. Thanks for your time anyway!

**Pull request closed without merging**
