### PR TITLE
iOS: Conditionally import RN headers to support all RN versions.

### PR DESCRIPTION
**Pull request by peacechen**
See #34

### CODE REVIEW

**Comment by Kerumen** [comment]
Before 0.40, it was `import "RCTBridge.h"` instead of `#import <RCTBridge.h>`.

https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c

Both work?

**Comment by peacechen** [comment]
You're absolutely right.  I've added another commit to fix that.

There's also another case if this library is used as a Pod in a Swift project.  Not sure if that's a valid use case here. Example:
https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePush.h

**Comment by Kerumen** [comment]
We'll leave this for now. If it's requested I'll make the change.

**Comment by peacechen** [comment]
I've been having trouble getting the header files to resolve in the parent project which uses react-native-awesome-card-io.  I noticed in your commit that initially added RN 0.40 header support, the header search paths were removed:
https://github.com/Kerumen/react-native-awesome-card-io/commit/df813181fc0c84c8b4cf8774be6ad908d55eeeee

How are you getting the parent project to pass on the header paths to the child project (native-awesome-card-io) ?

**Comment by Kerumen** [comment]
My project works fine without these header search paths. I made this change because they did it in the `react-native init` setup in 0.40 ([compare](https://github.com/ncuillery/rn-diff/compare/rn-0.39.2...rn-0.40.0)).

If we intend to support RN < 0.40 maybe we should re-add this.
Which version of RN do your project use?

**Comment by peacechen** [comment]
Currently we're stuck using RN 0.34.  Hoping to upgrade to the latest version but other tasks currently have priority.

Would you like me to create a separate PR or add to this one?

**Comment by Kerumen** [comment]
A separate one. Thanks :)

**Pull request merged**
