### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by emlynmac**
Hi,

I was evaluating this for use in a product, but the underlying native code is not good enough.  Here are the typescript defs for the module anyway!

Cheers,

### CODE REVIEW

**Comment by Kerumen** [comment]
Thanks for your PR!

What do you mean by "the underlying native code is not good enough"?

**Comment by emlynmac** [comment]
I mean that I got it all building and when testing against a credit card it just wasn’t good enough at reading the credit card. I looked at the repo and it seems I’m not alone here - there are some open issues about being able to read the card.

**Comment by Kerumen** [comment]
@emlynmac Thanks for your PR.
However the recommended way to add types to a library seems to be the project [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

Can you submit your PR there? Thanks!

**Comment by OnurVar** [comment]
Hi @Kerumen and @emlynmac,

I've added @emlynmac's type definitions to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). [Link](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-awesome-card-io)

You can install it via `yarn add @types/react-native-awesome-card-io --dev`. 

Thanks :)

**Comment by emlynmac** [comment]
Thanks! Glad they made it in and are providing use for peeps.

**Pull request closed without merging**
