### PR TITLE
Compatibility with React Native v0.60

### PR DESCRIPTION
**Pull request by Kerumen**
This PR also removes the card.io iOS SDK in the project.

### CODE REVIEW

**Comment by anishtr4** [comment]
Any plan to merge this to master soon?

**Comment by Kerumen** [comment]
@anishtr4 I need further tests to ensure everything works as expected.
Have you tried this on your project? I published [v0.9.0-rc.0](https://github.com/Kerumen/react-native-awesome-card-io/releases/tag/v0.9.0-rc.0) on npm if you want to try.

**Comment by Kerumen** [comment]
Published as [v0.9.0-rc.1](https://github.com/Kerumen/react-native-awesome-card-io/releases/tag/v0.9.0-rc.1) with some files refactoring!

**Comment by anishtr4** [comment]
> @anishtr4 I need further tests to ensure everything works as expected.
> Have you tried this on your project? I published [v0.9.0-rc.0](https://github.com/Kerumen/react-native-awesome-card-io/releases/tag/v0.9.0-rc.0) on npm if you want to try.



Tried it from the "upgrade-RN-v0.60" branch, and go it working without any issues. I didn't get much time to test fully.

**Comment by sepeterson** [comment]
> Seeing the following with Xcode 11.1, RN 0.61.1
> 
> linker_error

For anyone else running into this issue, it's because we had use `use_frameworks!` in our Podfile.

We got around it by downloading and adding the [CardIO SDK](https://github.com/card-io/card.io-iOS-SDK) to our project and referencing it in our Podfile like so:

```
pod 'CardIO', :path => './card.io-iOS-SDK-master'
```
And editing the CardIO SDK as shown here https://github.com/card-io/card.io-iOS-SDK/pull/284

**Comment by LinusU** [comment]
Seems to be working great, would be nice to get this merged and releases as a normal release 👍

**Comment by AleksandrZhukov** [comment]
@Kerumen nice job 👍, any plans to merge it?

**Comment by Kerumen** [comment]
Thanks everyone for the tests. This is now published as [v0.9.0](https://www.npmjs.com/package/react-native-awesome-card-io/v/0.9.0)!

**Pull request merged**
